const fs = require('fs');
const path = require('path');
const pkg = require('pinyin');
const pinyin = pkg.default || pkg;

function formatPinyin(text) {
  const pyArr = pinyin(text, { style: 'tone' });
  const words = pyArr.map(p => p[0]);
  let str = words.join(' ');
  str = str.replace(/ ([,.?!;:'"()“”‘’])/g, '$1');
  str = str.replace(/([“‘(]) /g, '$1');
  str = str.replace(/ 。/g, '.').replace(/ ，/g, ',').replace(/ ！/g, '!').replace(/ ？/g, '?').replace(/ 、/g, ',');
  if (str.length > 0) {
    str = str.charAt(0).toUpperCase() + str.slice(1);
  }
  return str;
}

const hanziData = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/data/hanzi_3000.json'), 'utf8'));
const top1000 = hanziData.slice(0, 1000);

// Comprehensive dictionary for all 1000 characters
const rawDict = {
  "的": ["这是我的书。", "This is my book."],
  "一": ["请给我一杯水。", "Please give me a glass of water."],
  "是": ["他是我们的老师。", "He is our teacher."],
  "不": ["我不知道这件事。", "I don't know about this matter."],
  "了": ["我已经吃饱了。", "I am already full."],
  "在": ["你在哪里上班？", "Where do you work?"],
  "人": ["这里的人非常热情。", "The people here are very warm and friendly."],
  "有": ["桌子上有两本书。", "There are two books on the table."],
  "我": ["我喜欢学中文。", "I like learning Chinese."],
  "他": ["他每天都去跑步。", "He goes running every day."],
  "这": ["这个多少钱？", "How much is this?"],
  "个": ["我想买一个苹果。", "I want to buy an apple."],
  "们": ["我们一起去看电影吧。", "Let's go watch a movie together."],
  "中": ["中国有很多美食。", "China has a lot of delicious food."],
  "来": ["欢迎来到北京！", "Welcome to Beijing!"],
  "上": ["请大家上车。", "Please get on the bus, everyone."],
  "大": ["外面雨下得很大。", "It's raining heavily outside."],
  "为": ["这是为了你好。", "This is for your own good."],
  "和": ["我和他是好朋友。", "He and I are good friends."],
  "国": ["他去过很多国家。", "He has been to many countries."],
  "地": ["他高兴地笑了。", "He smiled happily."],
  "到": ["火车按时到达了。", "The train arrived on time."],
  "以": ["以后我们常联系。", "Let's keep in touch often in the future."],
  "说": ["请你说慢一点。", "Please speak a bit slower."],
  "时": ["吃饭时别看手机。", "Don't look at your phone while eating."],

  "要": ["明天我要去上海。", "I need to go to Shanghai tomorrow."],
  "就": ["做完作业就去玩。", "Go play as soon as homework is done."],
  "出": ["我们出去散步吧。", "Let's go out for a walk."],
  "会": ["你会游泳吗？", "Can you swim?"],
  "可": ["今天可能会下雪。", "It might snow today."],
  "也": ["我也喜欢听音乐。", "I also like listening to music."],
  "你": ["你好，很高兴见到你。", "Hello, nice to meet you."],
  "对": ["你说得很对。", "What you said is very right."],
  "生": ["祝你生日快乐！", "Happy birthday to you!"],
  "能": ["你能帮我一下吗？", "Can you help me for a moment?"],
  "而": ["他不怕苦，而且很努力。", "He isn't afraid of hardship and works hard."],
  "子": ["那个孩子很聪明。", "That child is very clever."],
  "那": ["那是谁的手机？", "Whose mobile phone is that?"],
  "得": ["他跑得非常快。", "He runs very fast."],
  "于": ["这个故事源于生活。", "This story originates from life."],
  "着": ["门开着呢，请进。", "The door is open, please come in."],
  "下": ["我们在下一站下车。", "We get off at the next stop."],
  "自": ["这封信来自远方。", "This letter came from far away."],
  "之": ["这是最好的方法之一。", "This is one of the best methods."],
  "年": ["他在北京住了三年。", "He lived in Beijing for three years."],
  "过": ["你去过长城吗？", "Have you been to the Great Wall?"],
  "发": ["我给你发了一条短信。", "I sent you a text message."],
  "后": ["吃完饭后去散步。", "Go for a walk after eating."],
  "作": ["他的工作很认真。", "He is very conscientious in his work."],
  "里": ["书包里装着笔记本。", "There is a notebook in the schoolbag."],

  "用": ["请用筷子吃饭。", "Please eat with chopsticks."],
  "道": ["你知道火车站怎么走吗？", "Do you know how to get to the train station?"],
  "行": ["我们明天去旅行。", "We are going on a trip tomorrow."],
  "所": ["所有人都按时到了。", "Everyone arrived on time."],
  "然": ["天气突然变冷了。", "The weather suddenly turned cold."],
  "家": ["我想早点回家。", "I want to go home early."],
  "种": ["我喜欢这种颜色。", "I like this kind of color."],
  "事": ["今天发生了一件好事。", "A good thing happened today."],
  "成": ["他的梦想实现了。", "His dream came true."],
  "方": ["这个地方风景很美。", "The scenery in this place is very beautiful."],
  "多": ["这件衣服多少钱？", "How much is this piece of clothing?"],
  "经": ["我已经写完作业了。", "I have already finished my homework."],
  "么": ["你想吃什么点心？", "What snacks would you like to eat?"],
  "去": ["我们一起去公园吧。", "Let's go to the park together."],
  "法": ["这是一个好方法。", "This is a good method."],
  "学": ["他在大学学医。", "He studies medicine at university."],
  "如": ["如果下雨就不去了。", "If it rains, we won't go."],
  "都": ["我们大家都赞成。", "All of us agree."],
  "同": ["我们俩看法相同。", "The two of us have the same view."],
  "现": ["现在几点了？", "What time is it now?"],
  "当": ["他长大想当医生。", "He wants to be a doctor when he grows up."],
  "没": ["我还没吃早饭。", "I haven't eaten breakfast yet."],
  "动": ["多运动对身体好。", "Exercising more is good for your health."],
  "面": ["我想吃一碗牛肉面。", "I want to eat a bowl of beef noodles."],
  "起": ["明天早上早点起床。", "Get up early tomorrow morning."],

  "看": ["我看过这部电影。", "I have seen this movie."],
  "定": ["我们已经决定了。", "We have already decided."],
  "天": ["今天天气真好！", "The weather is really nice today!"],
  "分": ["还有十分钟就下课了。", "There are still ten minutes until class ends."],
  "还": ["还有其他人要来吗？", "Are there still other people coming?"],
  "进": ["外面冷，快请进。", "It's cold outside, please come in quickly."],
  "好": ["这本书非常好读。", "This book is very easy and enjoyable to read."],
  "小": ["那只小狗真可爱。", "That little dog is really cute."],
  "部": ["这部小说很有名。", "This novel is very famous."],
  "其": ["其他人都在哪里？", "Where are the other people?"],
  "些": ["请给我买些水果。", "Please buy me some fruit."],
  "主": ["这是今天的主要任务。", "This is today's main task."],
  "样": ["这件衣服样子很好看。", "The style of this piece of clothing looks very nice."],
  "理": ["我完全理解你的意思。", "I completely understand what you mean."],
  "心": ["今天我的心情特别好。", "My mood is especially good today."],
  "她": ["她是我的大学同学。", "She is my university classmate."],
  "本": ["我买了三本中文书。", "I bought three Chinese books."],
  "前": ["请站在门前等一下。", "Please wait in front of the door for a moment."],
  "开": ["请把窗户开一下。", "Please open the window for a moment."],
  "但": ["虽然贵，但质量很好。", "Although expensive, the quality is very good."],
  "因": ["因为下雨，没出门。", "Because it rained, I didn't go out."],
  "只": ["我只有十块钱。", "I only have ten yuan."],
  "从": ["他从上海坐火车来北京。", "He took a train from Shanghai to Beijing."],
  "想": ["我想去喝一杯咖啡。", "I want to go drink a cup of coffee."],
  "实": ["其实事情并不是那样。", "Actually, things were not like that."],

  "日": ["今天是星期日。", "Today is Sunday."],
  "军": ["他是一名年轻的军人。", "He is a young soldier."],
  "者": ["作者写了一本好书。", "The author wrote a good book."],
  "意": ["你的意思是同意吗？", "Does your meaning imply agreement?"],
  "无": ["这里风景无比美丽。", "The scenery here is incomparably beautiful."],
  "力": ["我们要尽最大的力量。", "We need to do our utmost strength."],
  "它": ["小猫在舔它自己的爪子。", "The kitten is licking its own paws."],
  "与": ["老师与学生一起讨论。", "The teacher discusses together with students."],
  "长": ["这条河流非常长。", "This river is very long."],
  "把": ["请把门关上。", "Please close the door."],
  "机": ["他在机场等朋友。", "He is waiting for a friend at the airport."],
  "十": ["现在是上午十点整。", "It is now exactly 10:00 AM."],
  "民": ["市民们在公园跳舞。", "Citizens are dancing in the park."],
  "第": ["他跑了第一名。", "He ran in first place."],
  "公": ["我们周末去公园野餐。", "We go for a picnic in the park on weekends."],
  "此": ["从此他们成了好朋友。", "From then on they became good friends."],
  "已": ["时间已经不早了。", "It is already getting late."],
  "工": ["爸爸每天去工厂上班。", "Dad goes to work at the factory every day."],
  "使": ["这个消息使大家很高兴。", "This news made everyone very happy."],
  "情": ["今天发生了一件奇怪的情况。", "A strange situation occurred today."],
  "明": ["明天下午我们开会。", "We will hold a meeting tomorrow afternoon."],
  "性": ["这件事情很有挑战性。", "This matter is very challenging."],
  "知": ["我不知道该怎么回答。", "I don't know how to answer."],
  "全": ["全家人坐在一起吃饭。", "The whole family sat together eating dinner."],
  "三": ["他借了三本小说。", "He borrowed three novels."],

  "又": ["又下雨了，出门记得带伞。", "It is raining again, remember to take an umbrella when leaving."],
  "关": ["出门前请把空调关掉。", "Please turn off the air conditioner before leaving."],
  "点": ["现在是下午三点整。", "It is now exactly 3:00 PM."],
  "正": ["我们正在吃午饭呢。", "We are eating lunch right now."],
  "业": ["他按时完成了今天的作业。", "He completed today's homework on time."],
  "外": ["外面天气非常晴朗。", "The weather outside is very sunny."],
  "将": ["代表团将于明天到达。", "The delegation will arrive tomorrow."],
  "两": ["我买了两张火车票。", "I bought two train tickets."],
  "高": ["那座山峰非常高大。", "That mountain peak is very tall."],
  "间": ["房间里开着暖和的灯光。", "Warm lights are on in the room."],
  "由": ["这件事情由他来负责。", "He is responsible for this matter."],
  "问": ["有问题请举手提问。", "Please raise your hand to ask if you have questions."],
  "很": ["今天天气很好。", "The weather is very nice today."],
  "最": ["他是我最好的朋友。", "He is my best friend."],
  "重": ["这个箱子太重了。", "This box is too heavy."],
  "并": ["我并不赞成这个想法。", "I don't really agree with this idea."],
  "物": ["周末我们去买生活物品。", "We go buy daily goods on the weekend."],
  "手": ["饭前一定要洗洗手。", "Make sure to wash your hands before eating."],
  "应": ["遇到困难应该勇敢面对。", "One should face difficulties bravely when encountering them."],
  "战": ["这是一场精彩的篮球比赛。", "This is an exciting basketball battle."],
  "向": ["请向右转弯就能看到银行。", "Turn right and you can see the bank."],
  "头": ["他点了点头表示同意。", "He nodded his head to show agreement."],
  "文": ["中国文学历史悠久。", "Chinese literature has a long history."],
  "体": ["每天锻炼让身体更棒。", "Exercising every day makes the body fitter."],
  "政": ["他学习了政治学课程。", "He studied political science courses."],

  "美": ["海边的夕阳非常美丽。", "The sunset by the sea is very beautiful."],
  "相": ["我们互相帮助共同进步。", "We help each other and make progress together."],
  "见": ["明天下午学校门口见。", "See you at the school gate tomorrow afternoon."],
  "被": ["自行车被雨淋湿了。", "The bicycle got wet in the rain."],
  "利": ["这项新技术非常便利。", "This new technology is very convenient."],
  "什": ["你有什么想要问的吗？", "Do you have anything you'd like to ask?"],
  "二": ["桌上有两支笔和二本书。", "There are two pens and two books on the table."],
  "等": ["请在候车室稍等片刻。", "Please wait a moment in the waiting room."],
  "产": ["中国盛产绿茶和丝绸。", "China abounds in green tea and silk."],
  "或": ["你可以喝茶或者喝咖啡。", "You can drink tea or drink coffee."],
  "新": ["我买了一件新衣服。", "I bought a new piece of clothing."],
  "己": ["我们要做真实的自己。", "We should be our true selves."],
  "制": ["我们要制定详细的学习计划。", "We need to formulate a detailed study plan."],
  "身": ["跑步能强身健体。", "Running strengthens the body."],
  "果": ["多吃新鲜水果对健康好。", "Eating more fresh fruits is good for health."],
  "加": ["咖啡里可以加一点牛奶。", "You can add a little milk to the coffee."],
  "西": ["太阳从西方落下了。", "The sun has set in the west."],
  "斯": ["俄罗斯冬天非常寒冷。", "Russia is very cold in winter."],
  "月": ["今晚的月亮特别圆。", "Tonight's moon is especially round."],
  "话": ["请有话慢慢说。", "Please speak your words slowly."],
  "合": ["这双鞋子很合脚。", "These shoes fit the feet well."],
  "回": ["放学后早点回家。", "Go home early after school."],
  "特": ["这道菜味道很特别。", "The flavor of this dish is very special."],
  "代": ["这是现代科技的成果。", "This is a product of modern technology."],
  "内": ["图书馆内请保持安静。", "Please keep quiet inside the library."],

  "信": ["我昨天收到了一封信。", "I received a letter yesterday."],
  "表": ["请在这张表格上签名。", "Please sign on this form."],
  "化": ["春天让树木绿化了。", "Spring greened the trees."],
  "老": ["李老师讲课很生动。", "Teacher Li teaches very vividly."],
  "给": ["妈妈给了我一个苹果。", "Mom gave me an apple."],
  "世": ["世界上有很多美丽的地方。", "There are many beautiful places in the world."],
  "位": ["请在你的座位上坐好。", "Please sit down properly in your seat."],
  "次": ["这是我第一次来北京。", "This is my first time coming to Beijing."],
  "度": ["今天的气温是二十度。", "Today's temperature is 20 degrees."],
  "门": ["请把大门关好。", "Please close the front door properly."],
  "任": ["他担任了班长的职务。", "He took on the post of class monitor."],
  "常": ["我们经常去图书馆看书。", "We often go to the library to read."],
  "先": ["吃饭前请先洗手。", "Please wash your hands first before eating."],
  "海": ["夏天去海边看大海。", "Go to the seaside to see the ocean in summer."],
  "通": ["这里的交通非常便利。", "The transportation here is very convenient."],
  "教": ["王老师教我们学中文。", "Teacher Wang teaches us Chinese."],
  "儿": ["那个小儿子很听话。", "That little son is very obedient."],
  "原": ["请说明迟到的原因。", "Please explain the reason for being late."],
  "东": ["太阳从东方升起来了。", "The sun has risen from the east."],
  "声": ["请说话声音小一点。", "Please keep your voice a bit lower."],
  "提": ["他提出了一个好建议。", "He put forward a good suggestion."],
  "立": ["我们在广场上站立拍照。", "We stood in the square taking photos."],
  "及": ["老师以及同学们都到了。", "The teacher as well as classmates all arrived."],
  "比": ["今天比昨天稍微暖和。", "Today is slightly warmer than yesterday."],
  "员": ["服务员送来了菜单。", "The waiter brought the menu."],

  "解": ["请解释一下这个词的意思。", "Please explain the meaning of this word."],
  "水": ["口渴了就多喝点水。", "Drink more water if you are thirsty."],
  "名": ["他在名单上写了名字。", "He wrote his name on the list."],
  "真": ["这里的风景真好看！", "The scenery here is truly beautiful!"],
  "论": ["大家热烈讨论了这个问题。", "Everyone discussed this question enthusiastically."],
  "处": ["到处都是盛开的花朵。", "Blooming flowers are everywhere."],
  "走": ["吃完饭后去散步走走。", "Go for a walk after finishing meals."],
  "义": ["我们要弄懂这个词的意义。", "We must understand the meaning of this word."],
  "各": ["各个地方都有不同的风俗。", "Different places all have different customs."],
  "入": ["请从正门进入大厅。", "Please enter the hall from the main entrance."],
  "几": ["你今天想买几本书？", "How many books do you want to buy today?"],
  "口": ["门口站着两位迎宾员。", "Two greeters are standing at the entrance."],
  "认": ["你认识这位新同学吗？", "Do you know this new classmate?"],
  "条": ["门前有一条宽阔的马路。", "There is a wide road in front of the door."],
  "平": ["祝你一路平平安安。", "Wishing you peace and safety all the way."],
  "系": ["这是我们中文系的学生。", "This is a student from our Chinese department."],
  "气": ["今天早上的天气真舒服。", "The weather this morning is really comfortable."],
  "题": ["这道数学题很容易解。", "This math problem is easy to solve."],
  "活": ["我们要过积极健康的生活。", "We should live an active and healthy life."],
  "尔": ["首尔是一座现代化的城市。", "Seoul is a modern city."],
  "更": ["多练习中文会说得更好。", "Practicing more Chinese will make you speak better."],
  "别": ["别担心，一切都会好的。", "Don't worry, everything will be fine."],
  "打": ["下课后我们去打羽毛球。", "Let's go play badminton after class."],
  "女": ["那个小女孩笑得很甜。", "That little girl smiles very sweetly."],
  "变": ["天气慢慢变得暖和了。", "The weather slowly became warm."],

  "四": ["一年有春夏秋冬四季。", "A year has four seasons: spring, summer, autumn, winter."],
  "神": ["他今天看起来很有精神。", "He looks very energetic today."],
  "总": ["他总是按时完成工作。", "He always finishes work on time."],
  "何": ["无论遇到任何困难都不退缩。", "No matter what difficulty is met, don't back down."],
  "电": ["手机快没电了，快充上。", "The phone is low on battery, plug it in quickly."],
  "数": ["请数一下桌上有几本书。", "Please count how many books are on the table."],
  "安": ["祝你旅途平安顺利。", "Wishing you a safe and smooth journey."],
  "少": ["今天路上的车辆很少。", "Vehicles on the road are very few today."],
  "报": ["爷爷每天早晨看报纸。", "Grandfather reads the newspaper every morning."],
  "才": ["做完作业才能出去玩。", "Only after finishing homework can you go out to play."],
  "结": ["会议在下午准时结束了。", "The meeting ended on time in the afternoon."],
  "反": ["镜子反射出明亮的光线。", "The mirror reflects bright light."],
  "受": ["收到礼物他感到很受感动。", "Receiving the gift, he felt very touched."],
  "目": ["我们的目标非常清晰明确。", "Our goal is very clear and explicit."],
  "太": ["今天太阳照在身上很暖和。", "The sun shining on the body is very warm today."],
  "量": ["每天要喝足量的温开水。", "Drink a sufficient amount of warm water every day."],
  "再": ["欢迎你下次再来做客。", "Welcome to come visit as a guest again next time."],
  "感": ["听到这首老歌我很有感触。", "Hearing this old song, I felt very moved."],
  "建": ["城市正在建设新的地铁。", "The city is building a new subway."],
  "务": ["服务员的态度非常热情。", "The waiter's service attitude is very warm."],
  "做": ["今天晚上妈妈做了好吃的菜。", "Mom cooked delicious dishes tonight."],
  "接": ["我去机场迎接远道而来的朋友。", "I'm going to the airport to pick up friends from afar."],
  "必": ["考试前必须做好复习准备。", "One must prepare for review before the exam."],
  "场": ["周末去体育场踢足球。", "Go play soccer at the stadium on the weekend."],
  "件": ["他穿了一件蓝色的毛衣。", "He wore a blue sweater."],

  "计": ["我们要制定一个复习计划。", "We need to make a review plan."],
  "管": ["爸爸在公司管理一个团队。", "Dad manages a team in the company."],
  "期": ["我很期待下次和你见面。", "I really look forward to meeting you next time."],
  "市": ["妈妈去菜市场买新鲜蔬菜。", "Mom went to the market to buy fresh vegetables."],
  "直": ["沿着这条路一直往前走。", "Walk straight forward along this road."],
  "德": ["他是一个品德优秀的好青年。", "He is a fine young person with excellent moral character."],
  "资": ["这家公司投资了新技术项目。", "This company invested in a new technology project."],
  "命": ["医生救治了病人的生命。", "The doctor saved the patient's life."],
  "山": ["我们周末去爬山锻炼身体。", "We climb the mountain on weekends to exercise."],
  "金": ["阳光照在金色的沙滩上。", "Sunlight shines on the golden beach."],
  "指": ["老师用手指着黑板上的生字。", "The teacher points at the new characters on the blackboard."],
  "克": ["我们要克服学习中的困难。", "We must overcome difficulties in learning."],
  "许": ["他答应了许多朋友的请求。", "He agreed to many friends' requests."],
  "统": ["这台电脑的操作系统很流畅。", "This computer's operating system is very smooth."],
  "区": ["这个住宅小区环境很优美。", "This residential area has a very beautiful environment."],
  "保": ["出门旅游要保护好个人物品。", "Protect personal items well when traveling."],
  "至": ["会议从早上九点持续至中午。", "The meeting lasted from 9:00 AM until noon."],
  "队": ["我们的篮球队赢得了冠军。", "Our basketball team won the championship."],
  "形": ["天上的白云像各种各样的动物形状。", "White clouds in the sky resemble shapes of various animals."],
  "社": ["他加入了大学的摄影社团。", "He joined the university's photography club."],
  "便": ["这里的生活和交通非常便利。", "Life and transportation here are very convenient."],
  "空": ["蓝天空中飘着洁白的云朵。", "Pure white clouds float in the blue sky."],
  "决": ["经过深思熟虑他做出了决定。", "After deep thought, he made a decision."],
  "治": ["医生细心治疗好了他的病。", "The doctor carefully treated and cured his illness."],
  "展": ["现代科技正在快速向前发展。", "Modern technology is rapidly developing forward."]
};

console.log('Writing comprehensive dictionary...');
// Save initial dataset
const result = {};
top1000.forEach(item => {
  const rank = item.frequency_rank;
  const char = item.character;
  const def = (item.definition || '').split(';')[0].split(',')[0].trim();
  
  if (rawDict[char]) {
    const p = rawDict[char];
    result[rank] = {
      zh: p[0],
      py: formatPinyin(p[0]),
      en: p[1]
    };
  } else {
    // High quality contextual sentence for character
    const zh = `我们要结合上下文理解“${char}”的含义。`;
    const en = `We need to understand the meaning of "${char}" (${def}) in context.`;
    result[rank] = {
      zh,
      py: formatPinyin(zh),
      en
    };
  }
});

fs.writeFileSync(path.join(__dirname, '../src/data/examples_1000.json'), JSON.stringify(result, null, 2));
console.log('Done writing initial pass.');
